### ISSUE TITLE
css override issue while using multiple fragments with same class name

### ISSUE THREAD

**Issue by awasthishivendra01** [tsnolan23/tailor-react-spa#1]
I have created two react fragments. and i have imported custom.css file for these two fragments having same class name, when i run on single template then css is overriding, Is there any solution for tailor component so that css having same class name in multiple apps do  not override.

Thanks in advance for your help!

**Comment by tsnolan23** [comment]
@awasthishivendra01 It sounds like what you're describing is not an issue with Tailor itself, but just how CSS behaves in general.  

To prevent the issue you're experiencing, you can check out scoping your CSS - applying hashes to each `className` to prevent conflicts in the global namespace.  There are several options for doing so when using webpack.

**Comment by awasthishivendra01** [comment]
@tsnolan23 , Yes i tried to fix that using sass it works for me, now there is no confliction.

Thank You!
