### ISSUE TITLE
Run independent Fragments

### ISSUE THREAD

**Issue by awasthishivendra01** [tsnolan23/tailor-react-spa#2]
Hi,

How can i run independent fragments, like http://localhost:8081, It should show chat fragment only.

Thanks!

**Comment by tsnolan23** [comment]
@awasthishivendra01 Not sure I understand the question. Are you asking how you could simply run only the single fragment without anything else?  

If that's the case, it's defeating the purpose of this example which requires at least 2 fragments - a bundle that serves up common dependencies and at least one fragment.

If you're looking to run the chat fragment independently, you'd want to remove the external dependency and allow weback to bundle it all together.

**Comment by awasthishivendra01** [comment]
@tsnolan23 , Right Now my tailor app is running on http://localhost:8080/contacts
and the child applications(fragments) runs on different ports, that are:
<fragment src="http://localhost:5000"></fragment>
<fragment src="http://localhost:8081"></fragment>
<fragment src="http://localhost:3000"></fragment>
When i hit child application(fragment) url http://localhost:5000 in the browser it is showing blank page with out any content.
Here i want my application work/run individually on the browser as well.

Thanks!

**Comment by awasthishivendra01** [comment]
@tsnolan23 , Right Now my tailor app is running on http://localhost:8080/contacts
and the child applications(fragments) runs on different ports, that are:
<fragment src="http://localhost:5000"></fragment>
<fragment src="http://localhost:8081"></fragment>
<fragment src="http://localhost:3000"></fragment>
When i hit child application(fragment) url http://localhost:5000 in the browser it is showing blank page with out any content.
Here i want my application work/run individually on the browser as well.

Thanks!

**Comment by awasthishivendra01** [comment]
@tsnolan23 , Right Now my tailor app is running on http://localhost:8080/contacts
and the child applications(fragments) runs on different ports, that are:
fragment src="http://localhost:5000"
fragment src="http://localhost:8081"
fragment src="http://localhost:3000"
When i hit child application(fragment) url http://localhost:5000 in the browser it is showing blank page with out any content.
Here i want my application work/run individually on the browser as well.

Thanks!

**Comment by tsnolan23** [comment]
@awasthishivendra01 Sorry for the delayed response...

The purpose of this repo is to have the fragments share common dependencies. The individual fragments, don't have all of the dependencies they require to run. The common bundle served up alongside them, serve up React and a few other dependencies they would need, so you wouldn't be able to run them individually.  

If you want to run them individually, you'd have to make another template with the common bundle and the single fragment to allow it to run.
