### ISSUE TITLE
Stuck at start-fragments

### ISSUE THREAD

**Issue by mdick1611** [tsnolan23/tailor-react-spa#3]
Hello, I was hoping to try out Tailor with this repository and then move on to build my own React app with it. I'm running into trouble getting it to start however, I properly followed steps 1-4 under 'How to Run', but step 5, running the start-fragments script, won't execute properly, the terminal just gets stuck immediately after the 'lerna run start' command, without any error thrown.

**Comment by armand1m** [comment]
I just added the flag `--parallel` to the `lerna run start` command in the main `package.json` and it runned all the services =) still, the tailor service layout is saying that there is no templates folder. 

I'll push a pull request with all the fix when I get this working =)

**Comment by armand1m** [comment]
Well, I was quite wrong. I was just going to the wrong url hehe When I accessed `http://localhost:8080/contacts`, it worked smoothly! 

The PR #4 fixes it :)

@tsnolan23 please merge it =)

**Comment by armand1m** [comment]
@tsnolan23 this at least fixes the broken experience most people are having while trying this.
