### ISSUE TITLE
Update this example.

### ISSUE THREAD

**Issue by armand1m** [tsnolan23/tailor-react-spa#5]
This example is highly outdated. These are some updated that would be nice:

- [x] Fix deprecated componentWillMount implementation
- [x] Fix components rendering wrong
- [ ] Add some tests
- [x] Implement Contact component
- [x] Update Contracts component to use CSS Grid Layout
- [x] Make it mobile friendly
- [x] Add a development watcher
- [x] Improve docs

**Comment by tsnolan23** [comment]
@armand1m I would say most of these a pretty unnecessary as the entire purpose of this repo was to show the implementation of Tailor.  The CSS and mobile-friendliness of the app is pretty much irrelevant.

**Comment by armand1m** [comment]
Ok, I just thought would be good to get it into a well-polished state so people can actually run without issues and have a better experience while trying this example. 

I'll keep those only in my repo and close this issue. Thanks anyway :slightly_smiling_face:

**Comment by tsnolan23** [comment]
I don't disagree with preventing issues running the example, but the CSS changes shouldn't affect that, nor do they add any value to the purpose of the repository, if you've already done them, push them up, that's fine, but not required.

**Comment by armand1m** [comment]
See PR #4 to get the fixes for people to run it and close issue #3. 
PR #6 contains my master branch with all these done, merge if you feel it is worth it =)
